### ISSUE TITLE
[Bug] Lib issues the calculation is incorrect

### ISSUE THREAD

**Issue by whats2000** [LegendsOfSky/PearlCalculatorCore#5] opened 2021-06-13 14:24 UTC
![1](https://user-images.githubusercontent.com/60466660/121811020-8f38f480-cc95-11eb-92fb-e04d97ce156d.png)
This a picture about the real testing result in 1.16.5
The thest in world result tick = 2 pos is at (1000.5826506180033, 150.81874999590218, 0)
The result from the calculator tick = 2 pos is at (1000.582650618024, 150.8484517986487, 0)
![2](https://user-images.githubusercontent.com/60466660/121811017-8811e680-cc95-11eb-8763-1115377f7fb1.png)
Here is the setting I test.
![3](https://user-images.githubusercontent.com/60466660/121811046-a4ae1e80-cc95-11eb-9006-6b412a1e96f3.png)
The test device I use with 3 command block
First one command is "script run loop(727,run('summon tnt -0.02 161 -0.02 {Motion:[0d,-10d,0d]}'))"
Second one command is "script run loop(727,run('summon tnt -0.02 161 0.02 {Motion:[0d,-10d,0d]}'))"
Third one command is "summon ender_pearl 0.0 150.84874999523163 0.0"
using carpet mod and extra to test

**Comment by LegendsOfSky** [comment] 2021-06-13 14:26
Report Rejected.
Reason : This reporter had not faced the problem himself.

**Comment by LegendsOfSky** [comment] 2021-06-13 14:37
Further Description :
This reporter is reporting issues others find and information might have been missing through a third person. Therefore, this issue will be closed soon unless the problem founder comment here.
![image](https://user-images.githubusercontent.com/67500141/121811783-fa83c600-cc97-11eb-8e61-5a6296584dd9.png)

**Comment by lntricate1** [comment] 2021-06-13 19:11
Ok hello, i experienced the issue. I think the error is that the game is written in Java and has a lot of casting to double and float which causes errors, but the lib is not in java so it doesn't have the same errors. One fix could be changing the pearl eyes from `0.25 * 0.85` to `0.2125000059604645`.

**Comment by whats2000** [comment] 2021-06-13 19:30
![unknown](https://user-images.githubusercontent.com/60466660/121819622-af31dd80-ccc0-11eb-9934-8de9de466607.png)
Here is the data using `0.2125000059604645` (same setting)

**Comment by lntricate1** [comment] 2021-06-13 19:42
Yeah, that new data looks very good, I think it did fix it.

**Comment by LegendsOfSky** [comment] 2021-06-13 20:57
Issue Confirmed. The eye height will be changed to a constant `0.2125000059604645` soon. Thanks for the report.
Note :
This Thread won't be close in 7 days unless a MCP check is finished.

**Comment by lntricate1** [comment] 2021-06-13 21:45
Also, since you will change the pearl eye height, you should also add some missing decimals to the TNT height. It's actually not `0.0612500011921`, it's `0.061250001192092896`

**Comment by LegendsOfSky** [comment] 2021-06-14 21:19
MCP Check finished. Result are correct in the same input.
Typical use should have a precision in 12 digits. Digits after 12 might not be correct dude to the way we normally obtain information.
Note :
This Issue will be closed soon.

**Comment by LegendsOfSky** [comment] 2021-06-14 21:30
To Intricate :
Before this Issue close, I want to apologize about the inconvenience caused by the Bug Report Rules.
The rules is used to prevent any information missing or distortion in transmitting.

It happened in discord. At that moment, ``whats2000_`` is sending your report to me, but most of the information were lost and resulting a hard time in guessing what reporters actually means and why this issues comes without any device to reproduce the whole problem. Therefore the rules has been setup and we need you to report for the issue.

I am very apologize for the inconvenience in reporting any Bugs. I hope you will understand.
Thanks for helping us to make this project a much better.

**Comment by memorydream** [comment] 2021-06-14 21:40
close this issue beacuse it fixed and new version released

**Closed by memorydream** 2021-06-14 21:40 UTC
Labels: bug, fixed

**Comment by memorydream** [comment] 2021-06-14 21:50
you might need to check about the value of Pearl Y Coordinate in settings which had changed from ```170.34722638929408``` to ```170.34722638929412```
